FROM node:18-alpine

WORKDIR /app

# Copiamos los archivos de dependencias
COPY package.json package-lock.json* ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código del frontend
COPY . .

# Exponemos el puerto de Vite
EXPOSE 5173

# Comando para iniciar React en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host"]